/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseFilter
 */
export interface BaseFilter {
    /**
     * 
     * @type {number}
     * @memberof BaseFilter
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof BaseFilter
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof BaseFilter
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof BaseFilter
     */
    skip: number;
}

export function BaseFilterFromJSON(json: any): BaseFilter {
    return BaseFilterFromJSONTyped(json, false);
}

export function BaseFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'skip': json['skip'],
    };
}

export function BaseFilterToJSON(value?: BaseFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'page': value.page,
        'pageSize': value.pageSize,
        'skip': value.skip,
    };
}

