/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CartItemDetail,
    CartItemDetailFromJSON,
    CartItemDetailFromJSONTyped,
    CartItemDetailToJSON,
} from './CartItemDetail';
import {
    ShopInfo,
    ShopInfoFromJSON,
    ShopInfoFromJSONTyped,
    ShopInfoToJSON,
} from './ShopInfo';

/**
 * 
 * @export
 * @interface CartItemDetailGroup
 */
export interface CartItemDetailGroup {
    /**
     * 
     * @type {ShopInfo}
     * @memberof CartItemDetailGroup
     */
    shop?: ShopInfo;
    /**
     * 
     * @type {Array<CartItemDetail>}
     * @memberof CartItemDetailGroup
     */
    items?: Array<CartItemDetail>;
}

export function CartItemDetailGroupFromJSON(json: any): CartItemDetailGroup {
    return CartItemDetailGroupFromJSONTyped(json, false);
}

export function CartItemDetailGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemDetailGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shop': !exists(json, 'shop') ? undefined : ShopInfoFromJSON(json['shop']),
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(CartItemDetailFromJSON)),
    };
}

export function CartItemDetailGroupToJSON(value?: CartItemDetailGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shop': ShopInfoToJSON(value.shop),
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(CartItemDetailToJSON)),
    };
}

