/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Category,
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface CategoryPair
 */
export interface CategoryPair {
    /**
     * 
     * @type {Category}
     * @memberof CategoryPair
     */
    parent?: Category;
    /**
     * 
     * @type {Category}
     * @memberof CategoryPair
     */
    child?: Category;
}

export function CategoryPairFromJSON(json: any): CategoryPair {
    return CategoryPairFromJSONTyped(json, false);
}

export function CategoryPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : CategoryFromJSON(json['parent']),
        'child': !exists(json, 'child') ? undefined : CategoryFromJSON(json['child']),
    };
}

export function CategoryPairToJSON(value?: CategoryPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': CategoryToJSON(value.parent),
        'child': CategoryToJSON(value.child),
    };
}

