/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Category,
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface CatGroup
 */
export interface CatGroup {
    /**
     * 
     * @type {Category}
     * @memberof CatGroup
     */
    parent?: Category;
    /**
     * 
     * @type {Array<Category>}
     * @memberof CatGroup
     */
    childs?: Array<Category>;
}

export function CatGroupFromJSON(json: any): CatGroup {
    return CatGroupFromJSONTyped(json, false);
}

export function CatGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : CategoryFromJSON(json['parent']),
        'childs': !exists(json, 'childs') ? undefined : ((json['childs'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function CatGroupToJSON(value?: CatGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': CategoryToJSON(value.parent),
        'childs': value.childs === undefined ? undefined : ((value.childs as Array<any>).map(CategoryToJSON)),
    };
}

