/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CatLabelBase,
    CatLabelBaseFromJSON,
    CatLabelBaseFromJSONTyped,
    CatLabelBaseToJSON,
} from './CatLabelBase';
import {
    Category,
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface CatLabelGroup
 */
export interface CatLabelGroup {
    /**
     * 
     * @type {CatLabelBase}
     * @memberof CatLabelGroup
     */
    label?: CatLabelBase;
    /**
     * 
     * @type {Category}
     * @memberof CatLabelGroup
     */
    parent?: Category;
    /**
     * 
     * @type {Category}
     * @memberof CatLabelGroup
     */
    child?: Category;
}

export function CatLabelGroupFromJSON(json: any): CatLabelGroup {
    return CatLabelGroupFromJSONTyped(json, false);
}

export function CatLabelGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatLabelGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : CatLabelBaseFromJSON(json['label']),
        'parent': !exists(json, 'parent') ? undefined : CategoryFromJSON(json['parent']),
        'child': !exists(json, 'child') ? undefined : CategoryFromJSON(json['child']),
    };
}

export function CatLabelGroupToJSON(value?: CatLabelGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': CatLabelBaseToJSON(value.label),
        'parent': CategoryToJSON(value.parent),
        'child': CategoryToJSON(value.child),
    };
}

