/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseFilter,
    BaseFilterFromJSON,
    BaseFilterFromJSONTyped,
    BaseFilterToJSON,
} from './BaseFilter';
import {
    Contact,
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
} from './Contact';

/**
 * 
 * @export
 * @interface FilterResultOfContact
 */
export interface FilterResultOfContact {
    /**
     * 
     * @type {Array<Contact>}
     * @memberof FilterResultOfContact
     */
    items?: Array<Contact>;
    /**
     * 
     * @type {BaseFilter}
     * @memberof FilterResultOfContact
     */
    filter?: BaseFilter;
}

export function FilterResultOfContactFromJSON(json: any): FilterResultOfContact {
    return FilterResultOfContactFromJSONTyped(json, false);
}

export function FilterResultOfContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterResultOfContact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ContactFromJSON)),
        'filter': !exists(json, 'filter') ? undefined : BaseFilterFromJSON(json['filter']),
    };
}

export function FilterResultOfContactToJSON(value?: FilterResultOfContact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ContactToJSON)),
        'filter': BaseFilterToJSON(value.filter),
    };
}

