/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseFilter,
    BaseFilterFromJSON,
    BaseFilterFromJSONTyped,
    BaseFilterToJSON,
} from './BaseFilter';
import {
    Qa,
    QaFromJSON,
    QaFromJSONTyped,
    QaToJSON,
} from './Qa';

/**
 * 
 * @export
 * @interface FilterResultOfQa
 */
export interface FilterResultOfQa {
    /**
     * 
     * @type {Array<Qa>}
     * @memberof FilterResultOfQa
     */
    items?: Array<Qa>;
    /**
     * 
     * @type {BaseFilter}
     * @memberof FilterResultOfQa
     */
    filter?: BaseFilter;
}

export function FilterResultOfQaFromJSON(json: any): FilterResultOfQa {
    return FilterResultOfQaFromJSONTyped(json, false);
}

export function FilterResultOfQaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterResultOfQa {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(QaFromJSON)),
        'filter': !exists(json, 'filter') ? undefined : BaseFilterFromJSON(json['filter']),
    };
}

export function FilterResultOfQaToJSON(value?: FilterResultOfQa | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(QaToJSON)),
        'filter': BaseFilterToJSON(value.filter),
    };
}

