/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseFilter,
    BaseFilterFromJSON,
    BaseFilterFromJSONTyped,
    BaseFilterToJSON,
} from './BaseFilter';
import {
    PostRecord,
    PostRecordFromJSON,
    PostRecordFromJSONTyped,
    PostRecordToJSON,
} from './PostRecord';

/**
 * 
 * @export
 * @interface FilterResultOfPostRecord
 */
export interface FilterResultOfPostRecord {
    /**
     * 
     * @type {Array<PostRecord>}
     * @memberof FilterResultOfPostRecord
     */
    items?: Array<PostRecord>;
    /**
     * 
     * @type {BaseFilter}
     * @memberof FilterResultOfPostRecord
     */
    filter?: BaseFilter;
}

export function FilterResultOfPostRecordFromJSON(json: any): FilterResultOfPostRecord {
    return FilterResultOfPostRecordFromJSONTyped(json, false);
}

export function FilterResultOfPostRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterResultOfPostRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(PostRecordFromJSON)),
        'filter': !exists(json, 'filter') ? undefined : BaseFilterFromJSON(json['filter']),
    };
}

export function FilterResultOfPostRecordToJSON(value?: FilterResultOfPostRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(PostRecordToJSON)),
        'filter': BaseFilterToJSON(value.filter),
    };
}

