/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseFilter,
    BaseFilterFromJSON,
    BaseFilterFromJSONTyped,
    BaseFilterToJSON,
} from './BaseFilter';
import {
    CartItemDetailGroup,
    CartItemDetailGroupFromJSON,
    CartItemDetailGroupFromJSONTyped,
    CartItemDetailGroupToJSON,
} from './CartItemDetailGroup';

/**
 * 
 * @export
 * @interface FilterResultOfCartItemDetailGroup
 */
export interface FilterResultOfCartItemDetailGroup {
    /**
     * 
     * @type {Array<CartItemDetailGroup>}
     * @memberof FilterResultOfCartItemDetailGroup
     */
    items?: Array<CartItemDetailGroup>;
    /**
     * 
     * @type {BaseFilter}
     * @memberof FilterResultOfCartItemDetailGroup
     */
    filter?: BaseFilter;
}

export function FilterResultOfCartItemDetailGroupFromJSON(json: any): FilterResultOfCartItemDetailGroup {
    return FilterResultOfCartItemDetailGroupFromJSONTyped(json, false);
}

export function FilterResultOfCartItemDetailGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterResultOfCartItemDetailGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(CartItemDetailGroupFromJSON)),
        'filter': !exists(json, 'filter') ? undefined : BaseFilterFromJSON(json['filter']),
    };
}

export function FilterResultOfCartItemDetailGroupToJSON(value?: FilterResultOfCartItemDetailGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(CartItemDetailGroupToJSON)),
        'filter': BaseFilterToJSON(value.filter),
    };
}

