/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseFilter,
    BaseFilterFromJSON,
    BaseFilterFromJSONTyped,
    BaseFilterToJSON,
} from './BaseFilter';
import {
    ShopInfo,
    ShopInfoFromJSON,
    ShopInfoFromJSONTyped,
    ShopInfoToJSON,
} from './ShopInfo';

/**
 * 
 * @export
 * @interface FilterResultOfShopInfo
 */
export interface FilterResultOfShopInfo {
    /**
     * 
     * @type {Array<ShopInfo>}
     * @memberof FilterResultOfShopInfo
     */
    items?: Array<ShopInfo>;
    /**
     * 
     * @type {BaseFilter}
     * @memberof FilterResultOfShopInfo
     */
    filter?: BaseFilter;
}

export function FilterResultOfShopInfoFromJSON(json: any): FilterResultOfShopInfo {
    return FilterResultOfShopInfoFromJSONTyped(json, false);
}

export function FilterResultOfShopInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterResultOfShopInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ShopInfoFromJSON)),
        'filter': !exists(json, 'filter') ? undefined : BaseFilterFromJSON(json['filter']),
    };
}

export function FilterResultOfShopInfoToJSON(value?: FilterResultOfShopInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ShopInfoToJSON)),
        'filter': BaseFilterToJSON(value.filter),
    };
}

