/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImgInfo
 */
export interface ImgInfo {
    /**
     * 
     * @type {string}
     * @memberof ImgInfo
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ImgInfo
     */
    thumb?: string;
    /**
     * 
     * @type {string}
     * @memberof ImgInfo
     */
    msg?: string;
    /**
     * 
     * @type {string}
     * @memberof ImgInfo
     */
    link?: string;
}

export function ImgInfoFromJSON(json: any): ImgInfo {
    return ImgInfoFromJSONTyped(json, false);
}

export function ImgInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImgInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': !exists(json, 'path') ? undefined : json['path'],
        'thumb': !exists(json, 'thumb') ? undefined : json['thumb'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'link': !exists(json, 'link') ? undefined : json['link'],
    };
}

export function ImgInfoToJSON(value?: ImgInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'thumb': value.thumb,
        'msg': value.msg,
        'link': value.link,
    };
}

