/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyVal
 */
export interface KeyVal {
    /**
     * 
     * @type {string}
     * @memberof KeyVal
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyVal
     */
    val?: string;
}

export function KeyValFromJSON(json: any): KeyVal {
    return KeyValFromJSONTyped(json, false);
}

export function KeyValFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyVal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'val': !exists(json, 'val') ? undefined : json['val'],
    };
}

export function KeyValToJSON(value?: KeyVal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'val': value.val,
    };
}

