/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Lang = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type Lang = typeof Lang[keyof typeof Lang];


export function LangFromJSON(json: any): Lang {
    return LangFromJSONTyped(json, false);
}

export function LangFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lang {
    return json as Lang;
}

export function LangToJSON(value?: Lang | null): any {
    return value as any;
}

