/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CartRecord,
    CartRecordFromJSON,
    CartRecordFromJSONTyped,
    CartRecordToJSON,
} from './CartRecord';
import {
    KeyVal,
    KeyValFromJSON,
    KeyValFromJSONTyped,
    KeyValToJSON,
} from './KeyVal';

/**
 * 
 * @export
 * @interface MasterOrder
 */
export interface MasterOrder {
    /**
     * 
     * @type {number}
     * @memberof MasterOrder
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MasterOrder
     */
    domainShopId: number;
    /**
     * 
     * @type {Date}
     * @memberof MasterOrder
     */
    createDateUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof MasterOrder
     */
    userIp?: string;
    /**
     * 
     * @type {number}
     * @memberof MasterOrder
     */
    contactId: number;
    /**
     * 
     * @type {Array<KeyVal>}
     * @memberof MasterOrder
     */
    userMsgs?: Array<KeyVal>;
    /**
     * 
     * @type {Array<CartRecord>}
     * @memberof MasterOrder
     */
    cartRecords?: Array<CartRecord>;
}

export function MasterOrderFromJSON(json: any): MasterOrder {
    return MasterOrderFromJSONTyped(json, false);
}

export function MasterOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): MasterOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'domainShopId': json['domainShopId'],
        'createDateUtc': (new Date(json['createDateUtc'])),
        'userIp': !exists(json, 'userIp') ? undefined : json['userIp'],
        'contactId': json['contactId'],
        'userMsgs': !exists(json, 'userMsgs') ? undefined : ((json['userMsgs'] as Array<any>).map(KeyValFromJSON)),
        'cartRecords': !exists(json, 'cartRecords') ? undefined : ((json['cartRecords'] as Array<any>).map(CartRecordFromJSON)),
    };
}

export function MasterOrderToJSON(value?: MasterOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'domainShopId': value.domainShopId,
        'createDateUtc': (value.createDateUtc.toISOString()),
        'userIp': value.userIp,
        'contactId': value.contactId,
        'userMsgs': value.userMsgs === undefined ? undefined : ((value.userMsgs as Array<any>).map(KeyValToJSON)),
        'cartRecords': value.cartRecords === undefined ? undefined : ((value.cartRecords as Array<any>).map(CartRecordToJSON)),
    };
}

