/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CatGroup,
    CatGroupFromJSON,
    CatGroupFromJSONTyped,
    CatGroupToJSON,
} from './CatGroup';
import {
    OrderDetail,
    OrderDetailFromJSON,
    OrderDetailFromJSONTyped,
    OrderDetailToJSON,
} from './OrderDetail';
import {
    PageMetas,
    PageMetasFromJSON,
    PageMetasFromJSONTyped,
    PageMetasToJSON,
} from './PageMetas';
import {
    PaymentAccount,
    PaymentAccountFromJSON,
    PaymentAccountFromJSONTyped,
    PaymentAccountToJSON,
} from './PaymentAccount';
import {
    ShopInfo,
    ShopInfoFromJSON,
    ShopInfoFromJSONTyped,
    ShopInfoToJSON,
} from './ShopInfo';

/**
 * 
 * @export
 * @interface OrderDetailViewModel
 */
export interface OrderDetailViewModel {
    /**
     * 
     * @type {OrderDetail}
     * @memberof OrderDetailViewModel
     */
    item?: OrderDetail;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailViewModel
     */
    paypalEnvironment?: string;
    /**
     * 
     * @type {PageMetas}
     * @memberof OrderDetailViewModel
     */
    pgMetas?: PageMetas;
    /**
     * 
     * @type {ShopInfo}
     * @memberof OrderDetailViewModel
     */
    shop?: ShopInfo;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailViewModel
     */
    pageName?: string;
    /**
     * 
     * @type {Array<CatGroup>}
     * @memberof OrderDetailViewModel
     */
    listingCatGroups?: Array<CatGroup>;
    /**
     * 
     * @type {Array<CatGroup>}
     * @memberof OrderDetailViewModel
     */
    itemTagCatGroups?: Array<CatGroup>;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailViewModel
     */
    currency?: string;
    /**
     * 
     * @type {Array<PaymentAccount>}
     * @memberof OrderDetailViewModel
     */
    payAccounts?: Array<PaymentAccount>;
}

export function OrderDetailViewModelFromJSON(json: any): OrderDetailViewModel {
    return OrderDetailViewModelFromJSONTyped(json, false);
}

export function OrderDetailViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDetailViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': !exists(json, 'item') ? undefined : OrderDetailFromJSON(json['item']),
        'paypalEnvironment': !exists(json, 'paypalEnvironment') ? undefined : json['paypalEnvironment'],
        'pgMetas': !exists(json, 'pgMetas') ? undefined : PageMetasFromJSON(json['pgMetas']),
        'shop': !exists(json, 'shop') ? undefined : ShopInfoFromJSON(json['shop']),
        'pageName': !exists(json, 'pageName') ? undefined : json['pageName'],
        'listingCatGroups': !exists(json, 'listingCatGroups') ? undefined : ((json['listingCatGroups'] as Array<any>).map(CatGroupFromJSON)),
        'itemTagCatGroups': !exists(json, 'itemTagCatGroups') ? undefined : ((json['itemTagCatGroups'] as Array<any>).map(CatGroupFromJSON)),
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'payAccounts': !exists(json, 'payAccounts') ? undefined : ((json['payAccounts'] as Array<any>).map(PaymentAccountFromJSON)),
    };
}

export function OrderDetailViewModelToJSON(value?: OrderDetailViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': OrderDetailToJSON(value.item),
        'paypalEnvironment': value.paypalEnvironment,
        'pgMetas': PageMetasToJSON(value.pgMetas),
        'shop': ShopInfoToJSON(value.shop),
        'pageName': value.pageName,
        'listingCatGroups': value.listingCatGroups === undefined ? undefined : ((value.listingCatGroups as Array<any>).map(CatGroupToJSON)),
        'itemTagCatGroups': value.itemTagCatGroups === undefined ? undefined : ((value.itemTagCatGroups as Array<any>).map(CatGroupToJSON)),
        'currency': value.currency,
        'payAccounts': value.payAccounts === undefined ? undefined : ((value.payAccounts as Array<any>).map(PaymentAccountToJSON)),
    };
}

