/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMetas
 */
export interface PageMetas {
    /**
     * 
     * @type {string}
     * @memberof PageMetas
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PageMetas
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PageMetas
     */
    image?: string;
}

export function PageMetasFromJSON(json: any): PageMetas {
    return PageMetasFromJSONTyped(json, false);
}

export function PageMetasFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMetas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function PageMetasToJSON(value?: PageMetas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'image': value.image,
    };
}

