/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    method?: string;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    orderId: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    stateCode: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    paymentId?: string;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'orderId': json['orderId'],
        'amount': json['amount'],
        'stateCode': json['stateCode'],
        'paymentId': !exists(json, 'paymentId') ? undefined : json['paymentId'],
    };
}

export function PaymentToJSON(value?: Payment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'method': value.method,
        'orderId': value.orderId,
        'amount': value.amount,
        'stateCode': value.stateCode,
        'paymentId': value.paymentId,
    };
}

