/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentAccount
 */
export interface PaymentAccount {
    /**
     * 
     * @type {string}
     * @memberof PaymentAccount
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAccount
     */
    info?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAccount
     */
    accountNo?: string;
}

export function PaymentAccountFromJSON(json: any): PaymentAccount {
    return PaymentAccountFromJSONTyped(json, false);
}

export function PaymentAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountType': !exists(json, 'accountType') ? undefined : json['accountType'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'accountNo': !exists(json, 'accountNo') ? undefined : json['accountNo'],
    };
}

export function PaymentAccountToJSON(value?: PaymentAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountType': value.accountType,
        'info': value.info,
        'accountNo': value.accountNo,
    };
}

