/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostLink
 */
export interface PostLink {
    /**
     * 
     * @type {number}
     * @memberof PostLink
     */
    seq: number;
    /**
     * 
     * @type {number}
     * @memberof PostLink
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    linkUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    linkTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    postId?: string;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    linkImg?: string;
    /**
     * 
     * @type {number}
     * @memberof PostLink
     */
    linkType: number;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    linkText?: string;
    /**
     * 
     * @type {string}
     * @memberof PostLink
     */
    imgThumb?: string;
}

export function PostLinkFromJSON(json: any): PostLink {
    return PostLinkFromJSONTyped(json, false);
}

export function PostLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'seq': json['seq'],
        'id': json['id'],
        'linkUrl': !exists(json, 'linkUrl') ? undefined : json['linkUrl'],
        'linkTitle': !exists(json, 'linkTitle') ? undefined : json['linkTitle'],
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'linkImg': !exists(json, 'linkImg') ? undefined : json['linkImg'],
        'linkType': json['linkType'],
        'linkText': !exists(json, 'linkText') ? undefined : json['linkText'],
        'imgThumb': !exists(json, 'imgThumb') ? undefined : json['imgThumb'],
    };
}

export function PostLinkToJSON(value?: PostLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seq': value.seq,
        'id': value.id,
        'linkUrl': value.linkUrl,
        'linkTitle': value.linkTitle,
        'postId': value.postId,
        'linkImg': value.linkImg,
        'linkType': value.linkType,
        'linkText': value.linkText,
        'imgThumb': value.imgThumb,
    };
}

