/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CategoryPair,
    CategoryPairFromJSON,
    CategoryPairFromJSONTyped,
    CategoryPairToJSON,
} from './CategoryPair';

/**
 * 
 * @export
 * @interface PostProp
 */
export interface PostProp {
    /**
     * 
     * @type {number}
     * @memberof PostProp
     */
    id: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof PostProp
     */
    catIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PostProp
     */
    postId?: string;
    /**
     * 
     * @type {Array<CategoryPair>}
     * @memberof PostProp
     */
    catPairs?: Array<CategoryPair>;
}

export function PostPropFromJSON(json: any): PostProp {
    return PostPropFromJSONTyped(json, false);
}

export function PostPropFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'catIds': !exists(json, 'catIds') ? undefined : json['catIds'],
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'catPairs': !exists(json, 'catPairs') ? undefined : ((json['catPairs'] as Array<any>).map(CategoryPairFromJSON)),
    };
}

export function PostPropToJSON(value?: PostProp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'catIds': value.catIds,
        'postId': value.postId,
        'catPairs': value.catPairs === undefined ? undefined : ((value.catPairs as Array<any>).map(CategoryPairToJSON)),
    };
}

