/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostProp,
    PostPropFromJSON,
    PostPropFromJSONTyped,
    PostPropToJSON,
} from './PostProp';

/**
 * 
 * @export
 * @interface PriceInfo
 */
export interface PriceInfo {
    /**
     * 
     * @type {number}
     * @memberof PriceInfo
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PriceInfo
     */
    cost: number;
    /**
     * 
     * @type {number}
     * @memberof PriceInfo
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof PriceInfo
     */
    propId?: number;
    /**
     * 
     * @type {string}
     * @memberof PriceInfo
     */
    postId?: string;
    /**
     * 
     * @type {PostProp}
     * @memberof PriceInfo
     */
    prop?: PostProp;
    /**
     * 
     * @type {string}
     * @memberof PriceInfo
     */
    propCode?: string;
}

export function PriceInfoFromJSON(json: any): PriceInfo {
    return PriceInfoFromJSONTyped(json, false);
}

export function PriceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cost': json['cost'],
        'price': json['price'],
        'propId': !exists(json, 'propId') ? undefined : json['propId'],
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'prop': !exists(json, 'prop') ? undefined : PostPropFromJSON(json['prop']),
        'propCode': !exists(json, 'propCode') ? undefined : json['propCode'],
    };
}

export function PriceInfoToJSON(value?: PriceInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cost': value.cost,
        'price': value.price,
        'propId': value.propId,
        'postId': value.postId,
        'prop': PostPropToJSON(value.prop),
        'propCode': value.propCode,
    };
}

