/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PsCatLabel
 */
export interface PsCatLabel {
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    postId?: string;
    /**
     * 
     * @type {number}
     * @memberof PsCatLabel
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PsCatLabel
     */
    catId: number;
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    text0?: string;
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    text1?: string;
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PsCatLabel
     */
    code?: string;
    /**
     * 
     * @type {number}
     * @memberof PsCatLabel
     */
    seq: number;
    /**
     * 
     * @type {number}
     * @memberof PsCatLabel
     */
    stateCode: number;
}

export function PsCatLabelFromJSON(json: any): PsCatLabel {
    return PsCatLabelFromJSONTyped(json, false);
}

export function PsCatLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PsCatLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': !exists(json, 'postId') ? undefined : json['postId'],
        'id': json['id'],
        'catId': json['catId'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'text0': !exists(json, 'text0') ? undefined : json['text0'],
        'text1': !exists(json, 'text1') ? undefined : json['text1'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'seq': json['seq'],
        'stateCode': json['stateCode'],
    };
}

export function PsCatLabelToJSON(value?: PsCatLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'id': value.id,
        'catId': value.catId,
        'label': value.label,
        'text0': value.text0,
        'text1': value.text1,
        'userId': value.userId,
        'code': value.code,
        'seq': value.seq,
        'stateCode': value.stateCode,
    };
}

