/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Register
 */
export interface Register {
    /**
     * 
     * @type {number}
     * @memberof Register
     */
    domainRootId: number;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    phoneDistrictNum?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    password?: string;
}

export function RegisterFromJSON(json: any): Register {
    return RegisterFromJSONTyped(json, false);
}

export function RegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domainRootId': json['domainRootId'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'givenName': !exists(json, 'givenName') ? undefined : json['givenName'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneDistrictNum': !exists(json, 'phoneDistrictNum') ? undefined : json['phoneDistrictNum'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function RegisterToJSON(value?: Register | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domainRootId': value.domainRootId,
        'surname': value.surname,
        'givenName': value.givenName,
        'gender': value.gender,
        'email': value.email,
        'phoneDistrictNum': value.phoneDistrictNum,
        'phoneNumber': value.phoneNumber,
        'password': value.password,
    };
}

