/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    ShopCatLabel,
    ShopCatLabelFromJSON,
    ShopCatLabelFromJSONTyped,
    ShopCatLabelToJSON,
} from './ShopCatLabel';

/**
 * 
 * @export
 * @interface RetOfShopCatLabel
 */
export interface RetOfShopCatLabel {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfShopCatLabel
     */
    ok: boolean;
    /**
     * 
     * @type {ShopCatLabel}
     * @memberof RetOfShopCatLabel
     */
    value?: ShopCatLabel;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfShopCatLabel
     */
    msgs?: Array<Msg>;
}

export function RetOfShopCatLabelFromJSON(json: any): RetOfShopCatLabel {
    return RetOfShopCatLabelFromJSONTyped(json, false);
}

export function RetOfShopCatLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfShopCatLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : ShopCatLabelFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfShopCatLabelToJSON(value?: RetOfShopCatLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': ShopCatLabelToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

