/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DashProfile,
    DashProfileFromJSON,
    DashProfileFromJSONTyped,
    DashProfileToJSON,
} from './DashProfile';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfDashProfile
 */
export interface RetOfDashProfile {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfDashProfile
     */
    ok: boolean;
    /**
     * 
     * @type {DashProfile}
     * @memberof RetOfDashProfile
     */
    value?: DashProfile;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfDashProfile
     */
    msgs?: Array<Msg>;
}

export function RetOfDashProfileFromJSON(json: any): RetOfDashProfile {
    return RetOfDashProfileFromJSONTyped(json, false);
}

export function RetOfDashProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfDashProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : DashProfileFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfDashProfileToJSON(value?: RetOfDashProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': DashProfileToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

