/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    PriceInfo,
    PriceInfoFromJSON,
    PriceInfoFromJSONTyped,
    PriceInfoToJSON,
} from './PriceInfo';

/**
 * 
 * @export
 * @interface RetOfListOfPriceInfo
 */
export interface RetOfListOfPriceInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfListOfPriceInfo
     */
    ok: boolean;
    /**
     * 
     * @type {Array<PriceInfo>}
     * @memberof RetOfListOfPriceInfo
     */
    value?: Array<PriceInfo>;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfListOfPriceInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfListOfPriceInfoFromJSON(json: any): RetOfListOfPriceInfo {
    return RetOfListOfPriceInfoFromJSONTyped(json, false);
}

export function RetOfListOfPriceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfListOfPriceInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>).map(PriceInfoFromJSON)),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfListOfPriceInfoToJSON(value?: RetOfListOfPriceInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': value.value === undefined ? undefined : ((value.value as Array<any>).map(PriceInfoToJSON)),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

