/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FrontendCatLabel,
    FrontendCatLabelFromJSON,
    FrontendCatLabelFromJSONTyped,
    FrontendCatLabelToJSON,
} from './FrontendCatLabel';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfFrontendCatLabel
 */
export interface RetOfFrontendCatLabel {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfFrontendCatLabel
     */
    ok: boolean;
    /**
     * 
     * @type {FrontendCatLabel}
     * @memberof RetOfFrontendCatLabel
     */
    value?: FrontendCatLabel;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfFrontendCatLabel
     */
    msgs?: Array<Msg>;
}

export function RetOfFrontendCatLabelFromJSON(json: any): RetOfFrontendCatLabel {
    return RetOfFrontendCatLabelFromJSONTyped(json, false);
}

export function RetOfFrontendCatLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfFrontendCatLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : FrontendCatLabelFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfFrontendCatLabelToJSON(value?: RetOfFrontendCatLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': FrontendCatLabelToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

