/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FileRecord,
    FileRecordFromJSON,
    FileRecordFromJSONTyped,
    FileRecordToJSON,
} from './FileRecord';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfListOfFileRecord
 */
export interface RetOfListOfFileRecord {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfListOfFileRecord
     */
    ok: boolean;
    /**
     * 
     * @type {Array<FileRecord>}
     * @memberof RetOfListOfFileRecord
     */
    value?: Array<FileRecord>;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfListOfFileRecord
     */
    msgs?: Array<Msg>;
}

export function RetOfListOfFileRecordFromJSON(json: any): RetOfListOfFileRecord {
    return RetOfListOfFileRecordFromJSONTyped(json, false);
}

export function RetOfListOfFileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfListOfFileRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>).map(FileRecordFromJSON)),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfListOfFileRecordToJSON(value?: RetOfListOfFileRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': value.value === undefined ? undefined : ((value.value as Array<any>).map(FileRecordToJSON)),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

