/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FilterResultOfShopInfo,
    FilterResultOfShopInfoFromJSON,
    FilterResultOfShopInfoFromJSONTyped,
    FilterResultOfShopInfoToJSON,
} from './FilterResultOfShopInfo';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfFilterResultOfShopInfo
 */
export interface RetOfFilterResultOfShopInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfFilterResultOfShopInfo
     */
    ok: boolean;
    /**
     * 
     * @type {FilterResultOfShopInfo}
     * @memberof RetOfFilterResultOfShopInfo
     */
    value?: FilterResultOfShopInfo;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfFilterResultOfShopInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfFilterResultOfShopInfoFromJSON(json: any): RetOfFilterResultOfShopInfo {
    return RetOfFilterResultOfShopInfoFromJSONTyped(json, false);
}

export function RetOfFilterResultOfShopInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfFilterResultOfShopInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : FilterResultOfShopInfoFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfFilterResultOfShopInfoToJSON(value?: RetOfFilterResultOfShopInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': FilterResultOfShopInfoToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

