/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Contact,
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
} from './Contact';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfContact
 */
export interface RetOfContact {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfContact
     */
    ok: boolean;
    /**
     * 
     * @type {Contact}
     * @memberof RetOfContact
     */
    value?: Contact;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfContact
     */
    msgs?: Array<Msg>;
}

export function RetOfContactFromJSON(json: any): RetOfContact {
    return RetOfContactFromJSONTyped(json, false);
}

export function RetOfContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfContact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : ContactFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfContactToJSON(value?: RetOfContact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': ContactToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

