/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';

/**
 * 
 * @export
 * @interface RetOfObject
 */
export interface RetOfObject {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfObject
     */
    ok: boolean;
    /**
     * 
     * @type {object}
     * @memberof RetOfObject
     */
    value?: object;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfObject
     */
    msgs?: Array<Msg>;
}

export function RetOfObjectFromJSON(json: any): RetOfObject {
    return RetOfObjectFromJSONTyped(json, false);
}

export function RetOfObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfObjectToJSON(value?: RetOfObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': value.value,
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

