/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    ShopInfo,
    ShopInfoFromJSON,
    ShopInfoFromJSONTyped,
    ShopInfoToJSON,
} from './ShopInfo';

/**
 * 
 * @export
 * @interface RetOfShopInfo
 */
export interface RetOfShopInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfShopInfo
     */
    ok: boolean;
    /**
     * 
     * @type {ShopInfo}
     * @memberof RetOfShopInfo
     */
    value?: ShopInfo;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfShopInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfShopInfoFromJSON(json: any): RetOfShopInfo {
    return RetOfShopInfoFromJSONTyped(json, false);
}

export function RetOfShopInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfShopInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : ShopInfoFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfShopInfoToJSON(value?: RetOfShopInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': ShopInfoToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

