/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    PostLink,
    PostLinkFromJSON,
    PostLinkFromJSONTyped,
    PostLinkToJSON,
} from './PostLink';

/**
 * 
 * @export
 * @interface RetOfPostLink
 */
export interface RetOfPostLink {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfPostLink
     */
    ok: boolean;
    /**
     * 
     * @type {PostLink}
     * @memberof RetOfPostLink
     */
    value?: PostLink;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfPostLink
     */
    msgs?: Array<Msg>;
}

export function RetOfPostLinkFromJSON(json: any): RetOfPostLink {
    return RetOfPostLinkFromJSONTyped(json, false);
}

export function RetOfPostLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfPostLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : PostLinkFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfPostLinkToJSON(value?: RetOfPostLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': PostLinkToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

