/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    OrderInfo,
    OrderInfoFromJSON,
    OrderInfoFromJSONTyped,
    OrderInfoToJSON,
} from './OrderInfo';

/**
 * 
 * @export
 * @interface RetOfOrderInfo
 */
export interface RetOfOrderInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfOrderInfo
     */
    ok: boolean;
    /**
     * 
     * @type {OrderInfo}
     * @memberof RetOfOrderInfo
     */
    value?: OrderInfo;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfOrderInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfOrderInfoFromJSON(json: any): RetOfOrderInfo {
    return RetOfOrderInfoFromJSONTyped(json, false);
}

export function RetOfOrderInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfOrderInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : OrderInfoFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfOrderInfoToJSON(value?: RetOfOrderInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': OrderInfoToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

