/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    UserInfo,
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
} from './UserInfo';

/**
 * 
 * @export
 * @interface RetOfUserInfo
 */
export interface RetOfUserInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfUserInfo
     */
    ok: boolean;
    /**
     * 
     * @type {UserInfo}
     * @memberof RetOfUserInfo
     */
    value?: UserInfo;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfUserInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfUserInfoFromJSON(json: any): RetOfUserInfo {
    return RetOfUserInfoFromJSONTyped(json, false);
}

export function RetOfUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfUserInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : UserInfoFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfUserInfoToJSON(value?: RetOfUserInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': UserInfoToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

