/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    PostRecord,
    PostRecordFromJSON,
    PostRecordFromJSONTyped,
    PostRecordToJSON,
} from './PostRecord';

/**
 * 
 * @export
 * @interface RetOfPostRecord
 */
export interface RetOfPostRecord {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfPostRecord
     */
    ok: boolean;
    /**
     * 
     * @type {PostRecord}
     * @memberof RetOfPostRecord
     */
    value?: PostRecord;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfPostRecord
     */
    msgs?: Array<Msg>;
}

export function RetOfPostRecordFromJSON(json: any): RetOfPostRecord {
    return RetOfPostRecordFromJSONTyped(json, false);
}

export function RetOfPostRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfPostRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : PostRecordFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfPostRecordToJSON(value?: RetOfPostRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': PostRecordToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

