/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Msg,
    MsgFromJSON,
    MsgFromJSONTyped,
    MsgToJSON,
} from './Msg';
import {
    UserRoleInfo,
    UserRoleInfoFromJSON,
    UserRoleInfoFromJSONTyped,
    UserRoleInfoToJSON,
} from './UserRoleInfo';

/**
 * 
 * @export
 * @interface RetOfUserRoleInfo
 */
export interface RetOfUserRoleInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RetOfUserRoleInfo
     */
    ok: boolean;
    /**
     * 
     * @type {UserRoleInfo}
     * @memberof RetOfUserRoleInfo
     */
    value?: UserRoleInfo;
    /**
     * 
     * @type {Array<Msg>}
     * @memberof RetOfUserRoleInfo
     */
    msgs?: Array<Msg>;
}

export function RetOfUserRoleInfoFromJSON(json: any): RetOfUserRoleInfo {
    return RetOfUserRoleInfoFromJSONTyped(json, false);
}

export function RetOfUserRoleInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetOfUserRoleInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'value': !exists(json, 'value') ? undefined : UserRoleInfoFromJSON(json['value']),
        'msgs': !exists(json, 'msgs') ? undefined : ((json['msgs'] as Array<any>).map(MsgFromJSON)),
    };
}

export function RetOfUserRoleInfoToJSON(value?: RetOfUserRoleInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'value': UserRoleInfoToJSON(value.value),
        'msgs': value.msgs === undefined ? undefined : ((value.msgs as Array<any>).map(MsgToJSON)),
    };
}

