/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShopBase
 */
export interface ShopBase {
    /**
     * 
     * @type {number}
     * @memberof ShopBase
     */
    shopId: number;
    /**
     * 
     * @type {number}
     * @memberof ShopBase
     */
    stateCode: number;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    shopUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    shopName?: string;
    /**
     * 
     * @type {number}
     * @memberof ShopBase
     */
    catId: number;
    /**
     * 
     * @type {number}
     * @memberof ShopBase
     */
    viewCatId: number;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    intro?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    shopCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    domainName?: string;
    /**
     * 
     * @type {number}
     * @memberof ShopBase
     */
    repShopId: number;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    uiTheme?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    uiBody?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    uiListing?: string;
    /**
     * 
     * @type {string}
     * @memberof ShopBase
     */
    uiLogo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    pickupEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    ownPickupEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    tagFilterable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payCashEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payFpsEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payAtmEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payPalEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payMeEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payAliEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopBase
     */
    payWechatEnabled: boolean;
}

export function ShopBaseFromJSON(json: any): ShopBase {
    return ShopBaseFromJSONTyped(json, false);
}

export function ShopBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopId': json['shopId'],
        'stateCode': json['stateCode'],
        'shopUserId': !exists(json, 'shopUserId') ? undefined : json['shopUserId'],
        'shopName': !exists(json, 'shopName') ? undefined : json['shopName'],
        'catId': json['catId'],
        'viewCatId': json['viewCatId'],
        'intro': !exists(json, 'intro') ? undefined : json['intro'],
        'shopCode': !exists(json, 'shopCode') ? undefined : json['shopCode'],
        'domainName': !exists(json, 'domainName') ? undefined : json['domainName'],
        'repShopId': json['repShopId'],
        'uiTheme': !exists(json, 'uiTheme') ? undefined : json['uiTheme'],
        'uiBody': !exists(json, 'uiBody') ? undefined : json['uiBody'],
        'uiListing': !exists(json, 'uiListing') ? undefined : json['uiListing'],
        'uiLogo': !exists(json, 'uiLogo') ? undefined : json['uiLogo'],
        'pickupEnabled': json['pickupEnabled'],
        'ownPickupEnabled': json['ownPickupEnabled'],
        'tagFilterable': json['tagFilterable'],
        'payCashEnabled': json['payCashEnabled'],
        'payFpsEnabled': json['payFpsEnabled'],
        'payAtmEnabled': json['payAtmEnabled'],
        'payPalEnabled': json['payPalEnabled'],
        'payMeEnabled': json['payMeEnabled'],
        'payAliEnabled': json['payAliEnabled'],
        'payWechatEnabled': json['payWechatEnabled'],
    };
}

export function ShopBaseToJSON(value?: ShopBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shopId': value.shopId,
        'stateCode': value.stateCode,
        'shopUserId': value.shopUserId,
        'shopName': value.shopName,
        'catId': value.catId,
        'viewCatId': value.viewCatId,
        'intro': value.intro,
        'shopCode': value.shopCode,
        'domainName': value.domainName,
        'repShopId': value.repShopId,
        'uiTheme': value.uiTheme,
        'uiBody': value.uiBody,
        'uiListing': value.uiListing,
        'uiLogo': value.uiLogo,
        'pickupEnabled': value.pickupEnabled,
        'ownPickupEnabled': value.ownPickupEnabled,
        'tagFilterable': value.tagFilterable,
        'payCashEnabled': value.payCashEnabled,
        'payFpsEnabled': value.payFpsEnabled,
        'payAtmEnabled': value.payAtmEnabled,
        'payPalEnabled': value.payPalEnabled,
        'payMeEnabled': value.payMeEnabled,
        'payAliEnabled': value.payAliEnabled,
        'payWechatEnabled': value.payWechatEnabled,
    };
}

