/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShopCatTag
 */
export interface ShopCatTag {
    /**
     * 
     * @type {number}
     * @memberof ShopCatTag
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ShopCatTag
     */
    shopId: number;
    /**
     * 
     * @type {number}
     * @memberof ShopCatTag
     */
    catId: number;
}

export function ShopCatTagFromJSON(json: any): ShopCatTag {
    return ShopCatTagFromJSONTyped(json, false);
}

export function ShopCatTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopCatTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'shopId': json['shopId'],
        'catId': json['catId'],
    };
}

export function ShopCatTagToJSON(value?: ShopCatTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'shopId': value.shopId,
        'catId': value.catId,
    };
}

