/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UiTheme
 */
export interface UiTheme {
    /**
     * 
     * @type {string}
     * @memberof UiTheme
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof UiTheme
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof UiTheme
     */
    listing?: string;
}

export function UiThemeFromJSON(json: any): UiTheme {
    return UiThemeFromJSONTyped(json, false);
}

export function UiThemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UiTheme {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'theme': !exists(json, 'theme') ? undefined : json['theme'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'listing': !exists(json, 'listing') ? undefined : json['listing'],
    };
}

export function UiThemeToJSON(value?: UiTheme | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'theme': value.theme,
        'body': value.body,
        'listing': value.listing,
    };
}

