/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRoleInfo
 */
export interface UserRoleInfo {
    /**
     * 
     * @type {number}
     * @memberof UserRoleInfo
     */
    recordId: number;
    /**
     * 
     * @type {string}
     * @memberof UserRoleInfo
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof UserRoleInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserRoleInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleInfo
     */
    code?: string;
}

export function UserRoleInfoFromJSON(json: any): UserRoleInfo {
    return UserRoleInfoFromJSONTyped(json, false);
}

export function UserRoleInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordId': json['recordId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function UserRoleInfoToJSON(value?: UserRoleInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recordId': value.recordId,
        'userId': value.userId,
        'id': value.id,
        'name': value.name,
        'code': value.code,
    };
}

