/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MessageViewModel,
    MessageViewModelFromJSON,
    MessageViewModelToJSON,
} from '../models';

export interface MemBaseForgotPasswordBaseRequest {
    domainRootId?: number;
    surname?: string | null;
    givenName?: string | null;
    gender?: string | null;
    email?: string | null;
    phoneDistrictNum?: string | null;
    phoneNumber?: string | null;
    password?: string | null;
}

/**
 * 
 */
export class MemBaseApi extends runtime.BaseAPI {

    /**
     */
    async memBaseForgotPasswordBaseRaw(requestParameters: MemBaseForgotPasswordBaseRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<MessageViewModel>> {
        const queryParameters: any = {};

        if (requestParameters.domainRootId !== undefined) {
            queryParameters['domainRootId'] = requestParameters.domainRootId;
        }

        if (requestParameters.surname !== undefined) {
            queryParameters['surname'] = requestParameters.surname;
        }

        if (requestParameters.givenName !== undefined) {
            queryParameters['givenName'] = requestParameters.givenName;
        }

        if (requestParameters.gender !== undefined) {
            queryParameters['gender'] = requestParameters.gender;
        }

        if (requestParameters.email !== undefined) {
            queryParameters['email'] = requestParameters.email;
        }

        if (requestParameters.phoneDistrictNum !== undefined) {
            queryParameters['phoneDistrictNum'] = requestParameters.phoneDistrictNum;
        }

        if (requestParameters.phoneNumber !== undefined) {
            queryParameters['phoneNumber'] = requestParameters.phoneNumber;
        }

        if (requestParameters.password !== undefined) {
            queryParameters['password'] = requestParameters.password;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/MemBase`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageViewModelFromJSON(jsonValue));
    }

    /**
     */
    async memBaseForgotPasswordBase(requestParameters: MemBaseForgotPasswordBaseRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<MessageViewModel> {
        const response = await this.memBaseForgotPasswordBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
